services:
  - type: web
    name: raadspel
    env: rust
    buildCommand: cargo build --release
    startCommand: ./target/release/raadspelmetweb
    envVars:
      - key: RUST_LOG
        value: debug
    staticPublishPath: ./static
    healthCheckPath: /health
    autoDeploy: true